version: '3'
services:
  postgres:
    image: postgres:latest
    env_file: .env
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: .
    env_file: .env
    command: dev
    restart: on-failure
    volumes:
      - .:/app
      - storage:/app/storage
    depends_on:
      - postgres
    ports:
      - 8000:8000
  celery:
    image: remindme_app
    env_file: .env
    command: celery
    restart: on-failure
    volumes:
      - .:/app
  redis:
    image: redis
    env_file: .env
volumes:
  storage:
  database:
