# Generated by Django 3.1.4 on 2020-12-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='date_to_complete',
            field=models.DateField(),
        ),
    ]
