# Generated by Django 3.1.4 on 2020-12-13 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201213_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
