# Generated by Django 3.1.4 on 2020-12-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201213_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='date_to_complete',
            field=models.DateTimeField(),
        ),
    ]
